apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerized-react-deployment
spec:
  selector:
    matchLabels:
      app: dockerized-react
  replicas: 10 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: dockerized-react
    spec:
      containers:
      - name: dockerized-react
        image: aldinkapetanovic/dockerized-react:j
        ports:
        - containerPort: 3000
